### ISSUE TITLE
triangular arbitrage

### ISSUE THREAD

**Issue by onthetunnel** [BigBitsYouTube/BitMEXAssistant#55]
Hello , Thanks You for your cool bot !! and can you dev triangular arbitrage to this cool bot please ...

**Comment by Ashaman-** [comment]
This is a bot for Bitmex. How exactly do you envision triangular arbitrage working on a derivatives trading platform?

**Comment by BigBitsYouTube** [comment]
@onthetunnel I believe this is outside the scope of the project.  This feature may come in another product in the future.  I'm going to close it, but the idea is good and will consider it when expanding products.
